### ISSUE TITLE
-

### ISSUE THREAD

**Issue by fortoon** [Line777/Meteorological-data-center#1]
这跟课程的资料 可以分享一下吗

**Comment by Line777** [comment]
慕课上边有，可以找一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上10:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Line777/Meteorological-data-center] 欲求分享 (Issue #1)




 
这跟课程的资料 可以分享一下吗

**Comment by fortoon** [comment]
我知道 上面有 需要购买 我没有购买 我看这个代码 感觉 你购买了 所以问下 资料可以分享下吗
